services:
  backend:
    volumes: []
    ports: []

  bot:
    volumes: []
    profiles:
      - telegram

  celery_worker:
    volumes: []

  frontend:
    volumes: []
    command: npm start
    ports: []
    environment:
      - NODE_ENV=production

  postgres:
    ports: []

  redis:
    ports: []

  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
